### ISSUE TITLE
Cython or Python pep?

### ISSUE THREAD

**Issue by nthiery** [sagemath/PEP-functions#1]
Hi @jdemeyer!
Thanks for setting this up. Just to clarify: do you envision this as a potential PEP for Cython or Python?

(sorry for creating an issue just for this; I wish there was some better venue for posting small questions like this.)

**Comment by jdemeyer** [comment]
I wonder how you found out about the existence of this repo.

Anyway, it's a Python PEP.

**Comment by nthiery** [comment]
>    I wonder how you found out about the existence of this repo.

As owner of the SageMath github organization, I received an automatic
notification of the creation of this new repo :-)

>    Anyway, it's a Python PEP.

Ok!
